[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 410
  force = true
[[redirects]]
  from = "https://calckey.activitypub.cyou/index.html"
  to = "https://calckey.activitypub.cyou/index_acpb.html"
  status = 301
  force = true
